server:
  port: 8080

spring:
  application:
    name: react
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: 'sk-62469d2d37d5482c99f4b10c1f76f831'
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v1
